# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.


HEADERS += ./globalsettings.h \
    ./mainlistitem.h \
    ./ourtrackserv.h \
    ./databasecontrol.h
SOURCES += ./databasecontrol.cpp \
    ./main.cpp \
    ./ourtrackserv.cpp \
    ./serialization.cpp
